list = ["ABCD", 12, 55.87, "abcd"]
print("Current list :- ", list)
str = input("Enter element of append in string :- ")
list.append(str)
print("Reverse list :- ", list.reverse())
print("Remove element 12 from list :-")
list.remove(12)
print("New list is :- ", list)
print("Insert element 15 at index 1 in list :- ")
list.insert(1, 15)
print("New list is :- ", list)
print("List contains abcd :- ", list.__contains__("abcd"))
print("Length of list :- ",list.__len__())
print("Pop element from list :- ")
list.pop(4)
print("New list :- ", list)
print("Clear the list :- ")
list.clear()
print("New list :- ", (list))
